// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLMCptt4l-X5Pko9QwFuYawo_KUrnc44o',
    appId: '1:139810943069:web:6b67467df9e4bdc9699db4',
    messagingSenderId: '139810943069',
    projectId: 'flutter-chat-website',
    authDomain: 'flutter-chat-website.firebaseapp.com',
    storageBucket: 'flutter-chat-website.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCembvCDx8G1ZTiiLih2L9C3vwKzH2zfd0',
    appId: '1:139810943069:android:933374687b265c8a699db4',
    messagingSenderId: '139810943069',
    projectId: 'flutter-chat-website',
    storageBucket: 'flutter-chat-website.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7c10EZ6gek0oI5hmUeKRlbLMUWQ3QXEM',
    appId: '1:139810943069:ios:49b5252e566500b4699db4',
    messagingSenderId: '139810943069',
    projectId: 'flutter-chat-website',
    storageBucket: 'flutter-chat-website.appspot.com',
    iosBundleId: 'com.example.assignment6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7c10EZ6gek0oI5hmUeKRlbLMUWQ3QXEM',
    appId: '1:139810943069:ios:93239a9edb992e7b699db4',
    messagingSenderId: '139810943069',
    projectId: 'flutter-chat-website',
    storageBucket: 'flutter-chat-website.appspot.com',
    iosBundleId: 'com.example.assignment6.RunnerTests',
  );
}
